### ISSUE TITLE
How to deal with different races

### ISSUE THREAD

**Issue by jtxtina** [kr-colab/discoal#18]
I am wondering how to differentiate/simulate different races, say Japanese, European, American, Chinese, during discoal process?

**Comment by jtxtina** [comment]
In what part of commands they are different and how?

**Comment by andrewkern** [comment]
hi there-- discoal doesn't simulate particular human populations necessarily. to do that you need to give it command lines that you think specify a particular history. 

if you are interested in pre-implemented demographic histories please have a look at the stdpopsim project: stdpopsim.readthedocs.io/

**Comment by jtxtina** [comment]
Oh I see, so you base your, say TennesseEuro(Table S1 command lines) on the stdpopsim project?
