### ISSUE TITLE
Errors when using deterministic sweeps (-wd)

### ISSUE THREAD

**Issue by MattHartfield** [kr-colab/discoal#19]
Hi,

discoal is producing errors relating to population size changes when using the -wd command (deterministic sweeps), even though no population size changes are being defined.

Example command:
discoal 30 1 100000 -t 50 -r 50 -wd 0 -a 500 -x 0.5

Error produced:
"Error with event specification: you chose 1 or more population size changes with a determinstic sweep. Please us -ws flag instead". (There also seems to be a typo in 'deterministic'.)

Thanks for looking into this!

**Comment by andrewkern** [comment]
should be all set!
