### ISSUE TITLE
Selection start and multiple populations

### ISSUE THREAD

**Issue by stsmall** [kr-colab/discoal#24]
Hi @andrewkern,
I have a question about how to simulate selection after a population split. Namely, I want to train a model where selection can only start after a population split. My thought is that if I use commands like -p 2 2 2 and -ed 0.5 0 1 -ws 0 ... selection stops at time 0 (sampling time) and can only start after the split time going forward since the population under selection (here id 0) doesnt exist until after that time. Am I on the right track? 
thanks,
@stsmall

**Comment by andrewkern** [comment]
Hey there @stsmall-- right so at a time of 0.5 you are probably safe. expected fixation time at alpha=100 should be ~0.2 units of coalescent time, so as long as alpha > 100ish you should be good to go here.

**Comment by stsmall** [comment]
Thanks. Am I correct in assuming that selection on pop 1 (index 0) stops when it merges into pop2 (index 1) going back in time?

**Comment by stsmall** [comment]
ugh, sorry. Stops is not what I meant. Backwards, forwards ... anyway. Does the merging set a hard boundary for when selection can start?

**Comment by andrewkern** [comment]
it does not, however sweeps can only occur in pop0, so if all the lineages are moved to pop1 then they will be unaffected by the sweep
