### ISSUE TITLE
Error:  `currentTrajectory' failed

### ISSUE THREAD

**Issue by xhchauvet** [kr-colab/discoal#25]
When I run the command, the script often runs for a while and then ends with the following error
 **discoal_multipop.c:57: main: Assertion `currentTrajectory' failed**
especially when there are many -en parameters. Could you tell me why am I getting this error?  I generated the script using the generateSimLaunchScript.py tool in diploSHIC package.

**Comment by andrewkern** [comment]
sorry I somehow lost this issue.

so i think this must be a memory issue on your machine-- how much RAM do you have available?

**Comment by xhchauvet** [comment]
I guess so. I tried to run it on the computer cluster and allocate 20 CPU cores with 50Gb memory per CPU. But it still doesn't work.

**Comment by andrewkern** [comment]
Hi @xhchauvet -- did you get this sorted? If so I'll close this issue. thanks.
