### ISSUE TITLE
rho is per-base or for the whole locus?

### ISSUE THREAD

**Issue by melop** [kr-colab/discoal#26]
Dear Prof. Kern, could you clarify whether in discoal the rho parameter is per-base or should I multiply it by the length of the locus?

Rongfeng Cui
Thank you!

**Comment by andrewkern** [comment]
rho for `discoal` is the whole locus, i.e. rho / bp \times length

**Comment by melop** [comment]
Thanks!
Within a long locus, double crossing overs may reduce the realized recombination between snps at the ends of the locus. Should I simply multiply the rho/bp by length without considering this effect?

**Comment by andrewkern** [comment]
yes this should be fine
