### ISSUE TITLE
Simulating purifying selection 

### ISSUE THREAD

**Issue by melop** [kr-colab/discoal#27]
Dear Prof. Kern,

       I'm wondering if there is a way to use discoal to simulate purifying selection on a genomic region where deleterious mutations are being removed with a user defined alpha=4Ns. 
       Does it equal to setting a hard sweep occurred many generations ago? Would selection continue to act on the position specified by -x, removing deleterious mutations after the beneficial allele got fixed?

Best regards,
Rongfeng Cui

**Comment by andrewkern** [comment]
Hi @melop -

No, discoal won't simulate purifying selection. For that I recommend the excellent [SLiM package](https://messerlab.org/slim/)
