### ISSUE TITLE
sample size issue: need recompile

### ISSUE THREAD

**Issue by TehYangHwa** [kr-colab/discoal#28]
I just ran discoal with sample size 500. An error message showed that I need to recompile discoal with flag -DBIG. Could you advise me how to recompile discoal? Thanks.

**Comment by andrewkern** [comment]
hi @TehYangHwa -

you can edit the `Makefile` such that the discoal target is:

`$(CC) $(CFLAGS)  -o discoal discoal_multipop.c discoalFunctions.c ranlibComplete.c alleleTraj.c -lm -fcommon -DBIG`

and then recompile using make

**Comment by TehYangHwa** [comment]
Hi @andrewkern 
Thanks, that's really help!
